// 'use client'

import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";

import "./globals.css";
import { MyNav } from "@/components/MyNav";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Timotius Giovandi",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  const date = new Date()

  return (
    <html lang="en" suppressHydrationWarning>
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <MyNav />
          {children}
          <div>
            <footer className="font-mono text-sm text-gray-500/50 border-t mt-5 py-2 text-center">{date.getFullYear()} - Timotius Giovandi</footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
